apiVersion: v1
kind: Service
metadata:
  name: label-demo-service
spec:
  selector:
    app: label-demo
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

