apiVersion: v1
kind: Pod
metadata:
  name: label-demo-pod
  labels:
    app: label-demo
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

