apiVersion: v1
kind: Pod
metadata:
  name: priority-demo-pod
spec:
  priorityClassName: high-priority
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 3600"]

