apiVersion: v1
kind: Pod
metadata:
  name: pv-demo-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo Hello from the PV > /mnt/data/hello.txt; sleep 3600"]
      volumeMounts:
        - mountPath: "/mnt/data"
          name: demo-storage
  volumes:
    - name: demo-storage
      persistentVolumeClaim:
        claimName: demo-pvc

