apiVersion: v1
kind: Pod
metadata:
  name: toleration-demo-pod
spec:
  tolerations:
    - key: "key"
      operator: "Equal"
      value: "value"
      effect: "NoSchedule"
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 3600"]

