apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdb-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pdb-demo
  template:
    metadata:
      labels:
        app: pdb-demo
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

