apiVersion: v1
kind: Pod
metadata:
  name: probes-demo-pod
spec:
  containers:
    - name: liveness-readiness-demo
      image: nginx
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 2
        periodSeconds: 5

