# Secret Demo Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-demo
  template:
    metadata:
      labels:
        app: secret-demo
    spec:
      containers:
        - name: demo
          image: busybox
          command: ["sh", "-c", "env; sleep 3600"]
          env:
            - name: DEMO_SECRET
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: DEMO_SECRET

